FROM ohac/base

RUN apt-get -y install wget curl htop vim

# for cpuminer
RUN apt-get -y install git automake m4 libcurl4-openssl-dev make g++

# for coind
RUN apt-get -y install libboost1.55-all-dev libdb6.0++-dev libminiupnpc-dev
