FROM ubuntu

RUN echo "deb http://archive.ubuntu.com/ubuntu trusty main restricted universe" > /etc/apt/sources.list
RUN apt-get update
RUN apt-get upgrade -y

RUN apt-get install -y wget curl htop vim
